/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_colsm_CoLSM */

#ifndef _Included_site_ycsb_db_colsm_CoLSM
#define _Included_site_ycsb_db_colsm_CoLSM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_colsm_CoLSM
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_colsm_CoLSM_init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_colsm_CoLSM
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_colsm_CoLSM_close
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_colsm_CoLSM
 * Method:    put
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_colsm_CoLSM_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     site_ycsb_db_colsm_CoLSM
 * Method:    delete
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_colsm_CoLSM_delete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_colsm_CoLSM
 * Method:    get
 * Signature: ([B[[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_colsm_CoLSM_get
  (JNIEnv *, jobject, jbyteArray, jobjectArray);

/*
 * Class:     site_ycsb_db_colsm_CoLSM
 * Method:    scan
 * Signature: ([BI[[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_colsm_CoLSM_scan
  (JNIEnv *, jobject, jbyteArray, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
