/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_leveldb_LevelDB */

#ifndef _Included_site_ycsb_db_leveldb_LevelDB
#define _Included_site_ycsb_db_leveldb_LevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_close
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    put
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    delete
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_delete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    get
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_leveldb_LevelDB_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    scanStart
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_scanStart
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    scanNext
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_leveldb_LevelDB_scanNext
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    scanStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_scanStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
