/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_leveldb_LevelDB */

#ifndef _Included_site_ycsb_db_leveldb_LevelDB
#define _Included_site_ycsb_db_leveldb_LevelDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_leveldb_LevelDB_close
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    put
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_leveldb_LevelDB_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    delete
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_leveldb_LevelDB_delete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    get
 * Signature: ([B[[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_leveldb_LevelDB_get
  (JNIEnv *, jobject, jbyteArray, jobjectArray);

/*
 * Class:     site_ycsb_db_leveldb_LevelDB
 * Method:    scan
 * Signature: ([BI[[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_leveldb_LevelDB_scan
  (JNIEnv *, jobject, jbyteArray, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
